[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.0"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
time_weighted_staking = "3qbuonQKjYW5XhYWohpHu1trKazvr7UwBYP5xk9hKMF6"

[programs.devnet]
time_weighted_staking = "3qbuonQKjYW5XhYWohpHu1trKazvr7UwBYP5xk9hKMF6"

[programs.mainnet]
time_weighted_staking = "3qbuonQKjYW5XhYWohpHu1trKazvr7UwBYP5xk9hKMF6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "3qbuonQKjYW5XhYWohpHu1trKazvr7UwBYP5xk9hKMF6"
program = "target/deploy/time_weighted_staking.so"

[test.validator]
bind_address = "0.0.0.0"
url = "http://127.0.0.1:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899
gossip_port = 8001
dynamic_port_range = "8002-8020"

[workspace]
members = [
    "programs/*"
]

[build]
exclude = ["node_modules"] 