[toolchain]
anchor_version = "0.28.0"
solana_version = "1.17.0"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
aura_staking = "9SNiVmYxKDG6Y1uRs2e6ivmjsG49KPygvwqmNCooiw4m"

[programs.devnet]
aura_staking = "9SNiVmYxKDG6Y1uRs2e6ivmjsG49KPygvwqmNCooiw4m"

[programs.mainnet]
aura_staking = "9SNiVmYxKDG6Y1uRs2e6ivmjsG49KPygvwqmNCooiw4m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "dev-authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "9SNiVmYxKDG6Y1uRs2e6ivmjsG49KPygvwqmNCooiw4m"
program = "target/deploy/aura_staking.so"

[test.validator]
bind_address = "0.0.0.0"
url = "http://127.0.0.1:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899
gossip_port = 8001
dynamic_port_range = "8002-8020"

[workspace]
members = [
    "programs/*"
]

[build]
exclude = ["node_modules"] 